RefillStationMap/Item/urls.py
from django.urls import path,include
import Item.views as views

app_name = 'Item'

urlpatterns = [
    path('save',views.save,name='save'),
    path('',views.item,name='store'),

]

RefillStationMap/Map/urls.py
from django.urls import path,include
import Map.views as views

app_name = 'Map'

urlpatterns = [
    path('save',views.store,name='save'),
    path('',views.map,name='store'),

]

RefillStationMap/RefillStationMap/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls',namespace="Home")),
    path('map/',include('Map.urls',namespace="Map")),
    path('item/',include('Item.urls',namespace="Item")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RefillStationMap/main/urls.py
from django.urls import path,include
import main.views as views

app_name = 'Home'

urlpatterns = [
    path('',views.index,name='main'),
    path('about',views.about,name='about'),
    path('wallet',views.wallet,name='wallet'),
    path('visit',views.visit,name='visit'),
    path('board',views.board,name='board'),
    path('store',views.store,name='store'),
    path('app-components',views.components,name='Map')

]

RefillStationMap/Item/models.py
from django.db import models

# Create your models here.
# image,price,name,detail
class Item(models.Model):
    name = models.CharField(max_length=300)
    image = models.TextField()
    price = models.IntegerField()
    detail = models.TextField(unique=True)

RefillStationMap/Map/models.py
from tkinter import CASCADE
from unicodedata import category
from django.db import models

# Create your models here.
class Store(models.Model):
    name = models.CharField(max_length=100)
    site = models.TextField(unique=True)
    longitude = models.FloatField()
    latitude = models.FloatField()
    category = models.TextField() #카테고리도 여러종류일 수 있음
    sub_category = models.TextField()

RefillStationMap/main/models.py
from django.db import models

# Create your models here.

RefillStationMap/Item/views.py
from django.shortcuts import redirect, render
from Item.item_save import item_save
from Item.models import Item
from django.core.paginator import Paginator
# Create your views here.

def save(request):

    item_save()
    return redirect(request,'/')

def item(request):

    res_data={}

    items = Item.objects.all()

    page = int(request.GET.get("p", 1))
    pagenator = Paginator(items, 6)
    res_data["result_board"] = pagenator.get_page(page)

    name_board=[]
    # ui 상품 name 통일
    for i in items:
        # print(len(i.name))
        if len(i.name)>50:
            temp = i.name[:51]+"..."
            print(temp)
            name_board.append(temp)
        else:
            name_board.append(i.name)

    if request.method == "POST":

        filter1 = request.POST['filter1']
        filter2 = request.POST['filter2']
        filter3 = request.POST['filter3']
        
        #filter1
        price_low_filter = items.order_by('price')
        price_high_filter = items.order_by('-price')

        if filter1=="price_low":
            pagenator = Paginator(price_low_filter, 6)
            res_data["result_board"] = pagenator.get_page(page)
            return render(request,'item/products.html',res_data)
        if filter1=="price_high":
            pagenator = Paginator(price_high_filter, 6)
            res_data["result_board"] = pagenator.get_page(page)
            return render(request,'item/products.html',res_data)
        if filter1=="popular":
            pagenator = Paginator(price_low_filter, 6)
            res_data["result_board"] = pagenator.get_page(page)
            return render(request,'item/products.html',res_data)
        if filter1=="latest":
            pagenator = Paginator(price_low_filter, 6)
            res_data["result_board"] = pagenator.get_page(page)
            return render(request,'item/products.html',res_data)

        #filter2
        if filter1=="delivery_false":
            pagenator = Paginator(price_low_filter, 6)
            res_data["result_board"] = pagenator.get_page(page)
            return render(request,'item/products.html',res_data)
        if filter1=="delivery_true":
            pagenator = Paginator(price_low_filter, 6)
            res_data["result_board"] = pagenator.get_page(page)
            return render(request,'item/products.html',res_data)

        #filter3
        if filter3!="":
            pagenator = Paginator(price_low_filter, 6)
            res_data["result_board"] = pagenator.get_page(page)
            return render(request,'item/products.html',res_data)



    
        return render(request,'item/products.html',res_data)

        

    return render(request,'item/products.html',res_data)

RefillStationMap/Map/views.py
from unicodedata import category
from django.shortcuts import render
from Map.models import Store
from Map.location_to_lati_longi import change
from Map.store_save import stores as st
from Map.store_save import save_stores as savestore
from django.core import serializers
import json

# Create your views here.
def store(request):

    stores = savestore()
    print(stores)

    return render(request,'store.html')

def map(request):

    if request.method == "POST":

        keyword = request.POST['keyword']
        check = request.POST['radiocheck']
        print(keyword,check)
        print(type(keyword))

        res_data=[]#check한것이 있을떼
        res_data2=[]#keyword가 있을때
        stores = Store.objects.all()

        # 1. 사용자가 check한 카테고리를 필터링. => 식품 화장품 생활용품중 하나
        if check!="null" and keyword=="":
            print("check")
            for store in stores:
                category = json.loads(store.category)
                if check in category:
                    if store in stores:
                        res_data.append(store)
        elif (keyword!="") and (check=="null"):
            print("keyword")
            filter_stores = Store.objects.filter(name__contains = keyword)
            for store in filter_stores:
                res_data2.append(store)
        elif (keyword!="") and (check!="null"):
            #둘다 있을때
            for store in stores:
                category = json.loads(store.category)
                if check in category:
                    if store in stores:
                        res_data.append(store)
            filter_stores = Store.objects.filter(name__contains = keyword)
            for store in filter_stores:
                res_data2.append(store)
        else:
            # filter를 사용하지 않았을때 모두 나오게끔한다
            all_stores = Store.objects.all()
            stores_js = serializers.serialize("json", all_stores)
            return render(request,'store.html',{'res_data' : stores_js})

        res_data3=[]

        print(res_data)
        print(res_data2)
        if (keyword!='') and check!="null":
            for i in res_data:
                for j in res_data2:
                    if i==j:
                        res_data3.append(i)
                        print(i)
        elif len(res_data)!=0:
            print("elif")
            res_data3 = res_data
        else:
            print("else")
            res_data3 = res_data2
        
        stores_js = serializers.serialize("json", res_data3)
        

        return render(request,'store.html',{'res_data' : stores_js})
    else:
        stores = Store.objects.all()
        stores_js = serializers.serialize("json", stores)
        return render(request,'store.html',{'res_data' : stores_js})

RefillStationMap/main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    
    return render(request,'index.html')

def about(request):
    
    return render(request,'about.html')

def store(request):

    return render(request,'store.html')

def wallet(request):

    return render(request,'wallet.html')

def visit(request):

    return render(request,'visit.html')

def board(request):

    return render(request,'board.html')

def components(request):

    return render(request,'app-components.html')

RefillStationMap/templates/index__.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <title>내리사랑</title>
    <meta name="description" content="Mobilekit HTML Mobile UI Kit">
    <meta name="keywords" content="bootstrap 5, mobile template, cordova, phonegap, mobile, html" />
    <link rel="icon" type="image/png" href="{% static 'img/mark.png'%} " sizes="32x32">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/icon/192x192.png'%} ">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">RefillStation Map</span>
                <span class="site-heading-lower">RefillStation Map</span>
            </h1>
        </header>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
            <div class="container">
                <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="{% url 'Home:main' %}">RefillStation Map</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'Home:main' %}">Home</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'Home:about' %}">About</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'Item:store' %}">Products</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'Map:store' %}">Store</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <section class="page-section clearfix">
            <div class="container">
                <div class="intro">
                    <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src='{% static "assets/img/main.jpeg" %}' alt="..." />
                    <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-upper">ESG 경영을 위한</span>
                            <span class="section-heading-lower">RefillStation Map</span>
                        </h2>
                        <p class="mb-3">refillstation map을 제공함으로써, 친환경적인 소비를 도모합니다. 여러분들이 원하는 상품 및 마켓을 검색하여 리필스테이션을 방문하여 자연 친화적인 소비를 해주세요.</p>
                        <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Map:store' %}">Start</a></div>
                    </div>
                </div>
            </div>
        </section>
        <section class="page-section cta">
            <div class="container">
                <div class="row">
                    <div class="col-xl-9 mx-auto">
                        <div class="cta-inner bg-faded text-center rounded">
                            <h2 class="section-heading mb-4">
                                <span class="section-heading-upper">Our Promise</span>
                                <span class="section-heading-lower">To You</span>
                            </h2>
                            <p class="mb-0">네이버, 구글, 다음 등 지도에 표시되어있지 않은 리필스테이션을 여러분들에게 제공하기 위해 노력할 것입니다. 최대한 많은 사람들이 리필스테이션을 활용하게끔 해주는 웹사이트가 되도록 노력하겠습니다.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">Copyright &copy; RefillStation Map</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src='{% static "js/scripts.js" %};></script>
    </body>

</html>

RefillStationMap/templates/item/products_temp.html
{% load static %}

<div class="col-sm" style="text-align: center; ">
    <table class = "table table-hover text-center" >
      <thead class="thead-dark">
          <tr>
              <td>상품명</td>
              <td>가격</td>
              <td>이미지</td>
              <td>더보기</td>
          </tr>
      </thead>
      <tbody>
          {% for data in result_board%}
          <tr>            
              <td>{{data.name}}</td>
              <td>{{data.price}}</td>
              <td><img src="{{data.image}}"></td>
              <td><a href="{{data.detail}}">{{data.detail}}</a></td>
          </tr>
          {% endfor %}
      </tbody>
  </table>

RefillStationMap/templates/visit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="stylesheet" href='{% static "css/style.css" %}?after'>
    <link rel="stylesheet" href='{% static "css/visit.css" %}?after'>
    <link rel="icon" type="image/x-icon" href='{% static "img/icon.png" %}' />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
</head>
<body>
    <div class="wrap">
        <div class="greenContainer">
          <div>
            <div style="width:50px; height:40px; float: left; margin-right:10px;">
                <img src='{% static "img/sample/avatar/avatar1.jpg" %}' alt="image" width="50" height="50" class="imaged rounded">
            </div>
            <div style="width:80px; height:40px; float: left; margin-top: 15px;" class="name">이윤표님</div>
          </div>    
          <div class="modify">i</div>    
        </div>
        <div class="currentpoint">
            <div class="item">
                <div style="font-weight: bold;">영수증 인증 내역</div>
                <div class="number" style="font-size: 20px;">8 건</div>
            </div>
        </div>
    </div>
    <div class="listContainer" style="word-break:break-all;">
        <div class="icon">구매일 2022.09.14</div>
        <a href="#" class="item">
            <div><img class="rimg" src='{% static "img/sample/photo/receipt.jpg" %}'></div>
            <div class="text" style="margin-left: 20px;">돌멩이상점</br>
                <div style="color:black;font-size: 17px;">샴푸 리필</br>
                    <div class="text">100ml / 1+1</div>
                </div>          
            </div>
            <div class="right">+ 1000P</div>
        </a>
    </div>
    <div class="listContainer">
        <div class="icon">구매일 2022.09.12</div>
        <a href="#" class="item">
            <div><img class="rimg" src='{% static "img/sample/photo/receipt2.jpg" %}'></div>
            <div class="text" style="margin-left: 20px;">이니스프리 강남직영점</br>
                <div style="color:black;font-size: 17px;">래디어스 실크 플로스 생분해 오가닉 치실 </br>
                    <div class="text">2개</div>
                </div>          
            </div>
            <div class="right">+ 1000P</div>
        </a>
    </div>
    <div class="listContainer">
        <div class="icon">구매일 2022.09.09</div>
        <a href="#" class="item">
            <div><img class="rimg" src='{% static "img/sample/photo/receipt3.jpg" %}'></div>
            <div class="text" style="margin-left: 20px;">채움소</br>
                <div style="color:black;font-size: 17px;">친환경 욕조 클리너 / 에코스토어 섬유유연제</br>
                    <div class="text">200ml / 500ml</div>
                </div>          
            </div>
            <div class="right">+ 4000P</div>
        </a>
    </div>
    <div class="listContainer">
        <div class="icon">구매일 2022.09.05</div>
        <a href="#" class="item">
            <div><img class="rimg" src='{% static "img/sample/photo/receipt4.jpg" %}'></div>
            <div class="text" style="margin-left: 20px;">도돌이상점</br>
                <div style="color:black;font-size: 17px;">친환경 젖병 세정제 / 주방세제</br>
                    <div class="text">100ml / 200ml</div>
                </div>          
            </div>
            <div class="right">+ 2000P</div>
        </a>
    </div>
    <div class="listContainer">
        <div class="icon">구매일 2022.09.03</div>
        <a href="#" class="item">
            <div><img class="rimg" src='{% static "img/sample/photo/receipt5.jpg" %}'></div>
            <div class="text" style="margin-left: 20px;">바람가게</br>
                <div style="color:black;font-size: 17px;">깨끗한 샴푸 리필 어쩌구 저쩌구</br>
                    <div class="text">200ml</div>
                </div>          
            </div>
            <div class="right">+ 1000P</div>
        </a>
    </div>
    <div class="listContainer" style="word-break:break-all;">
        <div class="icon">구매일 2022.09.01</div>
        <a href="#" class="item">
            <div><img class="rimg" src='{% static "img/sample/photo/receipt6.jpg" %}'></div>
            <div class="text" style="margin-left: 20px;">그로잉 카페</br>
                <div style="color:black;font-size: 17px;">친환경 핸드워시 리필</br>
                    <div class="text">700ml</div>
                </div>          
            </div>
            <div class="right">+ 3000P</div>
        </a>
    </div>
    <div class="listContainer">
        <div class="icon">구매일 2022.08.31</div>
        <a href="#" class="item">
            <div><img class="rimg" src='{% static "img/sample/photo/receipt7.jpg" %}'></div>
            <div class="text" style="margin-left: 20px;">낯설여관 204호</br>
                <div style="color:black;font-size: 17px;">친환경 바디워시(바닐라코코넛향)</br>
                    <div class="text">150ml</div>
                </div>          
            </div>
            <div class="right">+ 2000P</div>
        </a>
    </div>
    <div class="listContainer">
        <div class="icon">구매일 2022.08.24</div>
        <a href="#" class="item">
            <div><img class="rimg" src='{% static "img/sample/photo/receipt8.jpg" %}'></div>
            <div class="text" style="margin-left: 20px;">송정마을카페이공</br>
                <div style="color:black;font-size: 17px;">컨디셔너 울트라 센서티브</br>
                    <div class="text">550ml</div>
                </div>          
            </div>
            <div class="right">+ 1000P</div>
        </a>
    </div>
    <div style="margin-bottom: 10%;">
        <ul class="pagination justify-content-center">
            <li class="page-item">
              <a class="page-link" href="{% url 'Home:about' %}">뒤로가기</a >
            </li>
        </ul>
    </div>
        <!-- app footer -->
        <div class="appFooter">
            <img src='{% static "img/logo1.png" %}' alt="icon" class="footer-logo">
            <div class="footer-title">
                Copyright © 코끼Refill <span class="yearNow"></span>. All Rights Reserved.
            </div>

            <div class="mt-2">
                <a href="#" class="btn btn-icon btn-sm btn-facebook">
                    <ion-icon name="logo-facebook"></ion-icon>
                </a>
                <a href="#" class="btn btn-icon btn-sm btn-twitter">
                    <ion-icon name="logo-twitter"></ion-icon>
                </a>
                <a href="#" class="btn btn-icon btn-sm btn-linkedin">
                    <ion-icon name="logo-linkedin"></ion-icon>
                </a>
                <a href="#" class="btn btn-icon btn-sm btn-instagram">
                    <ion-icon name="logo-instagram"></ion-icon>
                </a>
                <a href="#" class="btn btn-icon btn-sm btn-whatsapp">
                    <ion-icon name="logo-whatsapp"></ion-icon>
                </a>
                <a href="#" class="btn btn-icon btn-sm btn-secondary goTop">
                    <ion-icon name="arrow-up-outline"></ion-icon>
                </a>
            </div>
        </div>
        <!-- * app footer -->
    </div>
    <!-- App Bottom Menu -->
    <div class="appBottomMenu">
        <a href="{% url 'Home:main' %}" class="item active">  
            <div class="col">
                <!-- <ion-icon name="home-outline"></ion-icon> -->
                <img src='{% static "img/home.png" %}' style="width: 50px;">
            </div>
        </a>
        <a href="{% url 'Map:store' %}" class="item">
            <div class="col">
                <!-- <ion-icon name="map-outline"></ion-icon> -->
                <img src='{% static "img/map.png" %}' style="width: 50px;">
            </div>
        </a>
        <a href="{% url 'Home:board' %}" class="item">
            <div class="col">
                <!-- <ion-icon name="chatbubble-ellipses-outline"></ion-icon> -->
                <img src='{% static "img/chat.png" %}' style="width: 50px;">
                <span class="badge badge-danger">5</span>
            </div>
        </a>
        <a href="{% url 'Item:store' %}" class="item">
            <div class="col">
                <!-- <ion-icon name="leaf-outline"></ion-icon> -->
                <img src='{% static "img/product.png" %}' style="width: 50px;">
            </div>
        </a>
        <a href="{% url 'Home:about' %}" class="item">
            <div class="col">
                <!-- <ion-icon name="person-outline"></ion-icon> -->
                <img src='{% static "img/mypage.png" %}' style="width: 50px;">
            </div>
        </a>
    </div>
    <!-- * App Bottom Menu -->
        <!-- Ionicons -->
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    </body>
</html>
    

RefillStationMap/templates/wallet.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="stylesheet" href='{% static "css/style.css" %}?after'>
    <link rel="stylesheet" href='{% static "css/wallet.css" %}?after'>
    <link rel="icon" type="image/x-icon" href='{% static "img/icon.png" %}' />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
</head>
<body>
    <div class="wrap">
        <div class="greenContainer">
          <div>
            <div style="width:50px; height:40px; float: left; margin-right:10px;">
                <img src='{% static "img/sample/avatar/avatar1.jpg" %}' alt="image" width="50" height="50" class="imaged rounded">
            </div>
            <div style="width:80px; height:40px; float: left; margin-top: 15px;" class="name">이윤표님</div>
          </div>    
          <div class="modify">i</div>    
        </div>
        <div class="currentpoint">
            <div class="item">
                <div>현재 포인트</div>
                <ion-icon name="wallet-outline"></ion-icon>
                <div class="number">2100 원</div>
            </div>
        </div>
    </div>
    <div class="listContainer" style="word-break:break-all;">
        <a href="#" class="item">
            <div class="icon">구매완료 구매적립금 적립</br>
                <div class="text">+500P</div>
            </div>
            <div class="right">2022.09.14</div>
        </a>
    </div>
    <div class="listContainer">
        <a href="#" class="item">
            <div class="icon">출석이벤트 적립</br>
                <div class="text">+100P</div>
            </div>
            <div class="right">2022.09.10</div>
        </a>
    </div>
    <div class="listContainer">
        <a href="#" class="item">
            <div class="icon">방문인증 적립금 적립</br>
                <div class="text">+1000P</div>
            </div>
            <div class="right">2022.09.08</div>
        </a>
    </div>
    <div class="listContainer">
        <a href="#" class="item">
          <div class="icon">상품 구입시 적립금 결제 사용</br>
            <div class="text" style="color: red;">-1000P</div>
          </div>
          <div class="right">2022.09.03</div>
      </a>
    </div>
    <div class="listContainer">
      <a href="#" class="item">
          <div class="icon">리뷰 검수 통과 정립금</br>
            <div class="text">+500P</div>
          </div>
          <div class="right">2022.09.01</div>
      </a>
    </div>
    <div class="listContainer" style="word-break:break-all;">
        <a href="#" class="item">
            <div class="icon">구매완료 구매적립금 적립</br>
                <div class="text">+500P</div>
            </div>
            <div class="right">2022.08.31</div>
        </a>
    </div>
    <div class="listContainer">
        <a href="#" class="item">
          <div class="icon">상품 구입시 적립금 결제 사용</br>
            <div class="text" style="color: red;">-1500P</div>
          </div>
          <div class="right">2022.08.22</div>
      </a>
    </div>
    <div class="listContainer">
        <a href="#" class="item">
            <div class="icon">방문인증 적립금 적립</br>
                <div class="text">+2000P</div>
            </div>
            <div class="right">2022.08.15</div>
        </a>
    </div>
    <div style="margin-bottom: 10%;">
        <ul class="pagination justify-content-center">
            <li class="page-item">
              <a class="page-link" href="{% url 'Home:about' %}">뒤로가기</a >
            </li>
        </ul>
    </div>
        <!-- app footer -->
        <div class="appFooter">
            <img src='{% static "img/logo1.png" %}' alt="icon" class="footer-logo">
            <div class="footer-title">
                Copyright © RefillStation <span class="yearNow"></span>. All Rights Reserved.
            </div>
            <div>Mobilekit is PWA ready Mobile UI Kit Template.</div>
            Great way to start your mobile websites and pwa projects.

            <div class="mt-2">
                <a href="#" class="btn btn-icon btn-sm btn-facebook">
                    <ion-icon name="logo-facebook"></ion-icon>
                </a>
                <a href="#" class="btn btn-icon btn-sm btn-twitter">
                    <ion-icon name="logo-twitter"></ion-icon>
                </a>
                <a href="#" class="btn btn-icon btn-sm btn-linkedin">
                    <ion-icon name="logo-linkedin"></ion-icon>
                </a>
                <a href="#" class="btn btn-icon btn-sm btn-instagram">
                    <ion-icon name="logo-instagram"></ion-icon>
                </a>
                <a href="#" class="btn btn-icon btn-sm btn-whatsapp">
                    <ion-icon name="logo-whatsapp"></ion-icon>
                </a>
                <a href="#" class="btn btn-icon btn-sm btn-secondary goTop">
                    <ion-icon name="arrow-up-outline"></ion-icon>
                </a>
            </div>
        </div>
        <!-- * app footer -->
    </div>
     <!-- App Bottom Menu -->
     <div class="appBottomMenu">
        <a href="{% url 'Home:main' %}" class="item active">  
            <div class="col">
                <!-- <ion-icon name="home-outline"></ion-icon> -->
                <img src='{% static "img/home.png" %}' style="width: 50px;">
            </div>
        </a>
        <a href="{% url 'Map:store' %}" class="item">
            <div class="col">
                <!-- <ion-icon name="map-outline"></ion-icon> -->
                <img src='{% static "img/map.png" %}' style="width: 50px;">
            </div>
        </a>
        <a href="{% url 'Home:board' %}" class="item">
            <div class="col">
                <!-- <ion-icon name="chatbubble-ellipses-outline"></ion-icon> -->
                <img src='{% static "img/chat.png" %}' style="width: 30px;">
                <span class="badge badge-danger">5</span>
            </div>
        </a>
        <a href="{% url 'Item:store' %}" class="item">
            <div class="col">
                <!-- <ion-icon name="leaf-outline"></ion-icon> -->
                <img src='{% static "img/product.png" %}' style="width: 50px;">
            </div>
        </a>
        <a href="{% url 'Home:about' %}" class="item">
            <div class="col">
                <!-- <ion-icon name="person-outline"></ion-icon> -->
                <img src='{% static "img/mypage.png" %}' style="width: 50px;">
            </div>
        </a>
    </div>
    <!-- * App Bottom Menu -->
        <!-- Ionicons -->
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    </body>
</html>
    